### PR TITLE
Create arc.yml

### PR DESCRIPTION
**Pull request by bootstraponline**

### CODE REVIEW

**Comment by bootstraponline** [comment]
@bart84ek Can you see if you can get the `arc unit` tests to pass? From what I can tell, the arc unit tests fail on upstream (even with no changes).

**Comment by bart84ek** [comment]
@bootstraponline confirmed. They are failing since we started playing with arcaniast :(

**Comment by bootstraponline** [comment]
Even upstream unmodified fails for me.

**Comment by alexeagle** [comment]
Is there a CI for the upstream, and is it red also? maybe they run the tests with some suppressions on the cmdline or something, it's hard to imagine they can productively work on arc with a red CI

**Comment by bootstraponline** [comment]
>Is there a CI for the upstream, and is it red also? maybe they run the tests with some suppressions on the cmdline or something, it's hard to imagine they can productively work on arc with a red CI

I opened a phabricator support ticket to gather more information about upstream CI. Upstream unit tests are red, you can confirm by checking out the unmodified code and running `arc unit`. They may have some special setup or environmental configuration where the unit tests are passing.

**Review by alexeagle — APPROVED** [review]

**Pull request merged**
